baseURL: "https://viktorpopp.github.io/blog/"
title: "Viktor's Blog"
pagination:
  pagerSize: 5

theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Viktor's Blog"
  description: "Viktor Popp's blog on tech, coding, and creative projects."
  keywords: [Blog]
  author: "Viktor Popp"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
  
  homeInfoParams:
    Title: "👋 Welcome to my blog!"
    Content: "Hi, I'm Viktor Popp, a passionate software developer specializing in systems programming and operating system development. I'm the creator of InfinityOS, an experimental operating system written in Rust, designed to push the boundaries of performance, security, and modern design principles. With a strong foundation in Rust, I enjoy diving deep into low-level programming, exploring the intricacies of hardware-software interaction, and tackling the challenges of building robust systems from scratch. Inspired by projects like Philip Opperman’s OS tutorial and MOROS, I aim to make complex topics accessible to others while continuously learning and innovating. When I'm not writing code, you'll find me exploring emerging technologies, sharing knowledge with the developer community, or brainstorming new ways to optimize and scale systems. Let's build something extraordinary together!"

  socialIcons:
    - name: github  
      url: "https://github.com/ViktorPopp"
    - name: discord
      url: "https://discord.com/users/1236265571591520271"

  editPost:
    URL: "https://github.com/ViktorPopp/blog/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    style: monokai
